hhvm:
    image: brunoric/hhvm:deb
    expose:
        - "9000"
    environment:
        APP_ENV: local
        APP_DEBUG: true
        APP_KEY: hGkhblTO6UNTJ0vPB8EYMPo6CjPye5wU
    volumes:
        - ./src:/var/www/src
#    links:
#        - db

nginx:
    build: .
    ports:
        - "80:80"
    volumes_from:
        - hhvm
    links:
        - hhvm
#db:
#    image: mysql:5.6
#    ports:
#        - "3306:3306"
#    environment:
#        MYSQL_ROOT_PASSWORD: secret
